version: 2
aliases: [
  &dependency-paths [
    "node_modules",
    "packages",
    "checksum.txt",
    "~/.ssh",
  ],
  &output-paths [
    "packages",
    "checksum.txt",
  ],
]
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: lenconda/rushstack:0.0.2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: rush update
      - run: npm run checksum
      - save_cache:
          paths: *dependency-paths
          key: v1-dependencies-{{ checksum "checksum.txt" }}
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: rush build
      - save_cache:
          paths: *output-paths
          key: v1-dist-{{ checksum "checksum.txt" }}
  publish_packages:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dist-{{ checksum "checksum.txt" }}
            - v1-dependencies-{{ checksum "checksum.txt" }}
      - run: rush update
      - run: rush build
      - run: rush publish --apply
      - run: rush publish --publish --include-all
      - run: echo -e "$GPG_SECRET_KEY" | gpg --import
      - run: git config --global user.email i@lenconda.top
      - run: git config --global user.name "lenconda"
      - run: git config --global user.signingkey $GPG_KEY_ID
      - run: git config --global commit.gpgsign true
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git add -A && git commit -S -m "publish packages" && git push origin publish
workflows:
  version: 2
  npm_workflow:
    jobs:
      - install:
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
      - publish_packages:
          requires:
            - build
          filters:
            branches:
              only:
                - /^publish$/
            tags:
              only: /^publish\@.+$/
